#!/bin/bash
# Check nockchain status
# Generated by nockit setup

echo "=== Nockchain Status ==="
echo

echo "Mining process:"
if pgrep -f "nockchain mine" > /dev/null; then
    echo "✅ Mining is running"
    pgrep -f "nockchain mine" | head -1 | xargs ps -p
else
    echo "❌ Mining is not running"
fi

echo
echo "Network status:"
nockit network status 2>/dev/null || echo "❌ Network check failed"

echo
echo "System health:"
nockit monitor --format compact 2>/dev/null || echo "❌ Health check failed"
