#!/bin/bash
# Start nockchain mining
# Generated by nockit setup

set -e

CONFIG_DIR="$(dirname "$0")/.."
source "$CONFIG_DIR/.env"

if [ -z "$MINING_PUBKEY" ]; then
    echo "Error: MINING_PUBKEY not set in .env file"
    echo "Run: nockit wallet keygen"
    exit 1
fi

echo "Starting nockchain mining..."
echo "Public key: $MINING_PUBKEY"

nockchain mine --pubkey "$MINING_PUBKEY" \
    --bind-address "$BIND_ADDRESS" \
    --peer-port "$PEER_PORT"
