# Nockchain Network Peer Configuration
# 
# This file contains known stable peers for the nockchain network.
# These peers can be used for bootstrapping connections and ensuring
# network connectivity during mining and wallet operations.
#
# Usage:
#   - Include these peers in nockchain startup commands
#   - Reference in automated scripts and configuration
#   - Use for network connectivity testing and validation

[network]
name = "nockchain-mainnet"
protocol = "quic-v1"
default_port = 3006

# Primary stable peers for network bootstrapping
[[peers]]
address = "/ip4/95.216.102.60/udp/3006/quic-v1"
description = "Primary bootstrap peer"
region = "EU"
reliability = "high"

[[peers]]
address = "/ip4/65.108.123.225/udp/3006/quic-v1"
description = "Secondary bootstrap peer"
region = "EU"
reliability = "high"

[[peers]]
address = "/ip4/65.109.156.108/udp/3006/quic-v1"
description = "Tertiary bootstrap peer"
region = "EU"
reliability = "high"

[[peers]]
address = "/ip4/65.21.67.175/udp/3006/quic-v1"
description = "Quaternary bootstrap peer"
region = "EU"
reliability = "high"

[[peers]]
address = "/ip4/65.109.156.172/udp/3006/quic-v1"
description = "Additional EU peer"
region = "EU"
reliability = "medium"

# Cloud provider peers
[[peers]]
address = "/ip4/34.174.22.166/udp/3006/quic-v1"
description = "Google Cloud peer"
region = "US"
reliability = "high"
provider = "GCP"

[[peers]]
address = "/ip4/34.95.155.151/udp/30000/quic-v1"
description = "Google Cloud peer (alt port)"
region = "US"
reliability = "medium"
provider = "GCP"

[[peers]]
address = "/ip4/34.18.98.38/udp/30000/quic-v1"
description = "Google Cloud peer (alt port)"
region = "US"
reliability = "medium"
provider = "GCP"

# Additional network peers
[[peers]]
address = "/ip4/96.230.252.205/udp/3006/quic-v1"
description = "North American peer"
region = "US"
reliability = "medium"

[[peers]]
address = "/ip4/94.205.40.29/udp/3006/quic-v1"
description = "European peer"
region = "EU"
reliability = "medium"

[[peers]]
address = "/ip4/159.112.204.186/udp/3006/quic-v1"
description = "Additional peer"
region = "Unknown"
reliability = "medium"

[[peers]]
address = "/ip4/88.0.59.61/udp/3006/quic-v1"
description = "European peer"
region = "EU"
reliability = "medium"

[[peers]]
address = "/ip4/217.14.223.78/udp/3006/quic-v1"
description = "European peer"
region = "EU"
reliability = "medium"

# Peer selection recommendations
[recommendations]
minimum_peers = 3
preferred_peers = 5
max_peers = 10
bootstrap_timeout = 30
connection_retry_delay = 5

# Regional peer groups for optimized connectivity
[regions.eu]
name = "Europe"
peers = [
    "/ip4/95.216.102.60/udp/3006/quic-v1",
    "/ip4/65.108.123.225/udp/3006/quic-v1",
    "/ip4/65.109.156.108/udp/3006/quic-v1",
    "/ip4/65.21.67.175/udp/3006/quic-v1",
    "/ip4/65.109.156.172/udp/3006/quic-v1",
    "/ip4/94.205.40.29/udp/3006/quic-v1",
    "/ip4/88.0.59.61/udp/3006/quic-v1",
    "/ip4/217.14.223.78/udp/3006/quic-v1"
]

[regions.us]
name = "United States"
peers = [
    "/ip4/34.174.22.166/udp/3006/quic-v1",
    "/ip4/34.95.155.151/udp/30000/quic-v1",
    "/ip4/34.18.98.38/udp/30000/quic-v1",
    "/ip4/96.230.252.205/udp/3006/quic-v1"
]

[regions.global]
name = "Global (All Regions)"
peers = [
    "/ip4/95.216.102.60/udp/3006/quic-v1",
    "/ip4/65.108.123.225/udp/3006/quic-v1",
    "/ip4/65.109.156.108/udp/3006/quic-v1",
    "/ip4/65.21.67.175/udp/3006/quic-v1",
    "/ip4/34.174.22.166/udp/3006/quic-v1",
    "/ip4/96.230.252.205/udp/3006/quic-v1"
] 